# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/12816/Documents/School/Junior-Year/Spring-2021/CS-3353/Project4/s21-pa04-mikecuzzo_grantayers

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/12816/Documents/School/Junior-Year/Spring-2021/CS-3353/Project4/s21-pa04-mikecuzzo_grantayers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/12816/Documents/School/Junior-Year/Spring-2021/CS-3353/Project4/s21-pa04-mikecuzzo_grantayers/CMakeFiles /mnt/c/Users/12816/Documents/School/Junior-Year/Spring-2021/CS-3353/Project4/s21-pa04-mikecuzzo_grantayers//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/12816/Documents/School/Junior-Year/Spring-2021/CS-3353/Project4/s21-pa04-mikecuzzo_grantayers/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named s21_pa04_mikecuzzo_grantayers

# Build rule for target.
s21_pa04_mikecuzzo_grantayers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 s21_pa04_mikecuzzo_grantayers
.PHONY : s21_pa04_mikecuzzo_grantayers

# fast build rule for target.
s21_pa04_mikecuzzo_grantayers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build
.PHONY : s21_pa04_mikecuzzo_grantayers/fast

src/GraphEngine.o: src/GraphEngine.cpp.o
.PHONY : src/GraphEngine.o

# target to build an object file
src/GraphEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/GraphEngine.cpp.o
.PHONY : src/GraphEngine.cpp.o

src/GraphEngine.i: src/GraphEngine.cpp.i
.PHONY : src/GraphEngine.i

# target to preprocess a source file
src/GraphEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/GraphEngine.cpp.i
.PHONY : src/GraphEngine.cpp.i

src/GraphEngine.s: src/GraphEngine.cpp.s
.PHONY : src/GraphEngine.s

# target to generate assembly for a file
src/GraphEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/GraphEngine.cpp.s
.PHONY : src/GraphEngine.cpp.s

src/Kruskals.o: src/Kruskals.cpp.o
.PHONY : src/Kruskals.o

# target to build an object file
src/Kruskals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/Kruskals.cpp.o
.PHONY : src/Kruskals.cpp.o

src/Kruskals.i: src/Kruskals.cpp.i
.PHONY : src/Kruskals.i

# target to preprocess a source file
src/Kruskals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/Kruskals.cpp.i
.PHONY : src/Kruskals.cpp.i

src/Kruskals.s: src/Kruskals.cpp.s
.PHONY : src/Kruskals.s

# target to generate assembly for a file
src/Kruskals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/Kruskals.cpp.s
.PHONY : src/Kruskals.cpp.s

src/Prims.o: src/Prims.cpp.o
.PHONY : src/Prims.o

# target to build an object file
src/Prims.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/Prims.cpp.o
.PHONY : src/Prims.cpp.o

src/Prims.i: src/Prims.cpp.i
.PHONY : src/Prims.i

# target to preprocess a source file
src/Prims.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/Prims.cpp.i
.PHONY : src/Prims.cpp.i

src/Prims.s: src/Prims.cpp.s
.PHONY : src/Prims.s

# target to generate assembly for a file
src/Prims.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/Prims.cpp.s
.PHONY : src/Prims.cpp.s

src/UnionFind.o: src/UnionFind.cpp.o
.PHONY : src/UnionFind.o

# target to build an object file
src/UnionFind.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/UnionFind.cpp.o
.PHONY : src/UnionFind.cpp.o

src/UnionFind.i: src/UnionFind.cpp.i
.PHONY : src/UnionFind.i

# target to preprocess a source file
src/UnionFind.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/UnionFind.cpp.i
.PHONY : src/UnionFind.cpp.i

src/UnionFind.s: src/UnionFind.cpp.s
.PHONY : src/UnionFind.s

# target to generate assembly for a file
src/UnionFind.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/UnionFind.cpp.s
.PHONY : src/UnionFind.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/build.make CMakeFiles/s21_pa04_mikecuzzo_grantayers.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... s21_pa04_mikecuzzo_grantayers"
	@echo "... src/GraphEngine.o"
	@echo "... src/GraphEngine.i"
	@echo "... src/GraphEngine.s"
	@echo "... src/Kruskals.o"
	@echo "... src/Kruskals.i"
	@echo "... src/Kruskals.s"
	@echo "... src/Prims.o"
	@echo "... src/Prims.i"
	@echo "... src/Prims.s"
	@echo "... src/UnionFind.o"
	@echo "... src/UnionFind.i"
	@echo "... src/UnionFind.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

